import Link from "next/link";
import { HiOutlineArrowLeft, HiOutlineExclamationCircle } from "react-icons/hi";
import { RefundStatusButton, TransactionActionMenu } from "@/components/admin/transactions/transaction-action-menu";
import { TransactionConsistencyCard } from "@/components/admin/transactions/transaction-consistency-card";
import { TransactionEventsTimeline } from "@/components/admin/transactions/transaction-events-timeline";
import { TransactionStatusBadge } from "@/components/admin/transactions/transaction-status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDateTime } from "@/lib/format-date";
import { formatMoney } from "@/lib/products/format";
import { paymentProviderLabel, reviewPriorityLabel } from "@/lib/validations/transactions";
import type { TransactionDetailDto } from "@/types/transactions";

function Row({ label, value, mono = false }: { label: string; value: React.ReactNode; mono?: boolean }) { return <div className="flex items-start justify-between gap-4 border-b border-border/60 py-2 last:border-0"><dt className="shrink-0 text-muted-foreground">{label}</dt><dd className={`min-w-0 break-words text-right ${mono ? "font-mono text-xs" : ""}`}>{value ?? "—"}</dd></div>; }
export function TransactionDetail({ transaction }: { transaction: TransactionDetailDto }) {
  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6"><nav aria-label="Breadcrumb" className="text-xs text-muted-foreground"><Link href="/admin" className="hover:text-foreground">Admin</Link> / <Link href="/admin/transactions" className="hover:text-foreground">Transacciones</Link> / <span>{transaction.id.slice(0, 10)}…</span></nav>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><Button variant="ghost" size="icon-sm" render={<Link href="/admin/transactions" />} nativeButton={false} aria-label="Volver a transacciones"><HiOutlineArrowLeft className="size-4" /></Button><div className="space-y-2"><div className="flex flex-wrap items-center gap-2"><h1 className="font-heading text-2xl font-semibold tracking-tight">Transacción</h1><TransactionStatusBadge status={transaction.status} /><Badge variant="secondary">{paymentProviderLabel[transaction.provider]}</Badge></div><p className="font-mono text-xs text-muted-foreground">{transaction.id}</p><p className="text-sm text-muted-foreground">{formatMoney(transaction.amount, transaction.currency)} · Creada {formatDateTime(transaction.createdAt)} · Actualizada {formatDateTime(transaction.updatedAt)}</p></div></div><div className="flex gap-2"><Button variant="outline" size="sm" render={<Link href={`/admin/orders/${transaction.order.id}`} />} nativeButton={false}>Abrir pedido</Button><TransactionActionMenu transaction={transaction} /></div></header>
    {transaction.failureMessage ? <div role="alert" className="flex gap-2 rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive"><HiOutlineExclamationCircle className="size-5 shrink-0" /><div><p className="font-medium">Error de integración</p><p>{transaction.failureMessage}</p>{transaction.failureCode ? <p className="font-mono text-xs">{transaction.failureCode}</p> : null}</div></div> : null}
    {transaction.requiresReview ? <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-4"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">Revisión manual abierta</p>{transaction.reviewPriority ? <Badge variant="destructive">{reviewPriorityLabel[transaction.reviewPriority]}</Badge> : null}</div><p className="mt-1 text-sm text-muted-foreground">{transaction.reviewReason}</p>{transaction.reviewNote ? <p className="mt-1 text-sm">{transaction.reviewNote}</p> : null}<p className="mt-2 text-xs text-muted-foreground">{transaction.reviewActorEmail}{transaction.reviewCreatedAt ? ` · ${formatDateTime(transaction.reviewCreatedAt)}` : ""}</p></div> : null}
    <TransactionConsistencyCard issues={transaction.issues} />
    <div className="grid gap-6 lg:grid-cols-[1.35fr_1fr]"><div className="space-y-6">
      <section className="rounded-2xl border border-border bg-card p-4 sm:p-6"><h2 className="text-sm font-medium">Información de la transacción</h2><dl className="mt-3 text-sm"><Row label="ID interno" value={transaction.id} mono /><Row label="Proveedor" value={paymentProviderLabel[transaction.provider]} /><Row label="Estado local" value={<TransactionStatusBadge status={transaction.status} />} /><Row label="Monto" value={formatMoney(transaction.amount, transaction.currency)} /><Row label="Moneda" value={transaction.currency} /><Row label="Referencia externa" value={transaction.externalReference} mono /><Row label="Flow order" value={transaction.flowOrder} /><Row label="Commerce order" value={transaction.commerceOrder} mono /><Row label="Método" value={transaction.paymentMethod} /><Row label="Pagador" value={transaction.payerEmail} /><Row label="Pagada" value={transaction.paidAt ? formatDateTime(transaction.paidAt) : null} /><Row label="Confirmada" value={transaction.confirmedAt ? formatDateTime(transaction.confirmedAt) : null} /><Row label="Expira" value={transaction.expiresAt ? formatDateTime(transaction.expiresAt) : null} /><Row label="Reembolsado" value={formatMoney(transaction.refundAmount, transaction.currency)} /></dl></section>
      <section className="rounded-2xl border border-border bg-card p-4 sm:p-6"><h2 className="text-sm font-medium">Flow.cl</h2><dl className="mt-3 text-sm"><Row label="Estado proveedor" value={transaction.providerStatus} /><Row label="Última consulta" value={transaction.lastProviderCheckAt ? formatDateTime(transaction.lastProviderCheckAt) : "Nunca"} /><Row label="Flow order" value={transaction.flowOrder} /><Row label="Método" value={transaction.paymentMethod} /><Row label="Referencia" value={transaction.externalReference} mono /></dl><p className="mt-3 text-xs text-muted-foreground">El token se abrevia en el servidor. Las firmas, credenciales y payloads completos nunca se envían a esta vista.</p></section>
      <section className="rounded-2xl border border-border bg-card p-4 sm:p-6"><h2 className="mb-4 text-sm font-medium">Timeline</h2><TransactionEventsTimeline events={transaction.events} /></section>
    </div><aside className="space-y-6">
      <section className="rounded-2xl border border-border bg-card p-4 sm:p-6"><h2 className="text-sm font-medium">Resumen del pedido</h2><dl className="mt-3 text-sm"><Row label="Número" value={<Link className="text-primary hover:underline" href={`/admin/orders/${transaction.order.id}`}>#{transaction.order.id.slice(-10).toUpperCase()}</Link>} /><Row label="Estado" value={transaction.order.status} /><Row label="Cliente" value={transaction.order.customerName || "Sin nombre"} /><Row label="Email" value={transaction.order.email} /><Row label="Total" value={formatMoney(transaction.order.total, transaction.order.currency)} /><Row label="Moneda" value={transaction.order.currency} /><Row label="Fecha" value={formatDateTime(transaction.order.createdAt)} /><Row label="Ítems" value={transaction.order.itemsCount} /><Row label="Entregas" value={`${transaction.order.deliveriesCount}/${transaction.order.itemsCount}`} /><Row label="Estados entrega" value={transaction.order.deliveryStatuses.length ? transaction.order.deliveryStatuses.join(", ") : "Sin iniciar"} /><Row label="Transacciones exitosas" value={transaction.approvedPaymentsCount} /></dl></section>
      {transaction.refunds.length ? <section className="rounded-2xl border border-border bg-card p-4 sm:p-6"><h2 className="text-sm font-medium">Reembolsos</h2><ul className="mt-3 space-y-3">{transaction.refunds.map((refund) => <li key={refund.id} className="rounded-xl bg-muted/50 p-3 text-sm"><div className="flex items-center justify-between gap-2"><p className="font-medium">{formatMoney(refund.amount, refund.currency)}</p><Badge variant={refund.status === "ERROR" || refund.status === "REJECTED" ? "destructive" : "secondary"}>{refund.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{formatDateTime(refund.requestedAt)} · {refund.reason}</p>{refund.flowRefundOrder ? <p className="font-mono text-xs text-muted-foreground">{refund.flowRefundOrder}</p> : null}{["CREATED", "ACCEPTED", "ERROR"].includes(refund.status) ? <div className="mt-2"><RefundStatusButton refundId={refund.id} /></div> : null}</li>)}</ul></section> : null}
      {transaction.safeMetadata ? <section className="rounded-2xl border border-border bg-card p-4 sm:p-6"><h2 className="text-sm font-medium">Metadata segura</h2><dl className="mt-3 text-sm">{Object.entries(transaction.safeMetadata).map(([key, value]) => <Row key={key} label={key} value={String(value ?? "—")} />)}</dl></section> : null}
    </aside></div>
  </div>;
}
