import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { WebPushActions } from "@/components/admin/communications/web-push-actions";
import { WebPushForm } from "@/components/admin/communications/web-push-form";
import { WebPushPreview } from "@/components/admin/communications/web-push-preview";
import { getWebPushNotification } from "@/lib/communications/web-push-queries";
import { webPushStatusLabels } from "@/lib/communications/status";
export default async function WebPushDetailPage({ params }: { params: Promise<{ id: string }> }) { const row = await getWebPushNotification((await params).id); if (!row) notFound(); return <div className="space-y-5"><header className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="font-heading text-2xl font-semibold">{row.name}</h1><Badge variant="secondary">{webPushStatusLabels[row.status]}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Creada por {row.createdByEmail} · {new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(row.createdAt))}</p></div><WebPushActions id={row.id} status={row.status} /></header>{row.status === "DRAFT" ? <WebPushForm initial={{ id: row.id, name: row.name, title: row.title, body: row.body, kind: row.kind as "OPERATIONAL" | "MARKETING" | "SECURITY", targetUrl: row.targetUrl, iconUrl: row.iconUrl, imageUrl: row.imageUrl, priority: row.priority, ttlSeconds: row.ttlSeconds }} /> : <div className="grid gap-5 lg:grid-cols-[1fr_380px]"><div className="grid gap-3 sm:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Resultados</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Destinatarios</p><p className="text-xl font-semibold">{row.recipients}</p></div><div><p className="text-muted-foreground">Entregadas</p><p className="text-xl font-semibold">{row.delivered}</p></div><div><p className="text-muted-foreground">Clics</p><p className="text-xl font-semibold">{row.clicked}</p></div><div><p className="text-muted-foreground">Fallidas</p><p className="text-xl font-semibold">{row.failed}</p></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Programación y proveedor</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Zona horaria: {row.timezone}</p><p>Programada: {row.scheduledAt ? new Intl.DateTimeFormat("es-CL", { dateStyle: "full", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(row.scheduledAt)) : "No"}</p><p>Enviada: {row.sentAt ? new Intl.DateTimeFormat("es-CL", { dateStyle: "full", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(row.sentAt)) : "No"}</p><p>ID OneSignal: {row.externalId ?? "Aún no asignado"}</p>{row.providerError ? <p className="text-destructive">Error: {row.providerError}</p> : null}</CardContent></Card></div><WebPushPreview title={row.title} body={row.body} iconUrl={row.iconUrl ?? undefined} imageUrl={row.imageUrl ?? undefined} /></div>}</div>; }
