-- CreateEnum
CREATE TYPE "StoreStatus" AS ENUM ('OPEN', 'READ_ONLY', 'MAINTENANCE', 'CLOSED');

-- CreateTable
CREATE TABLE "store_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "storeName" TEXT NOT NULL DEFAULT 'Nicodigos',
    "legalName" TEXT,
    "shortDescription" TEXT,
    "supportEmail" TEXT NOT NULL DEFAULT 'soporte@nicodigos.cl',
    "senderName" TEXT NOT NULL DEFAULT 'Nicodigos',
    "replyToEmail" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#E15707',
    "timezone" TEXT NOT NULL DEFAULT 'America/Santiago',
    "locale" TEXT NOT NULL DEFAULT 'es',
    "country" TEXT NOT NULL DEFAULT 'CL',
    "defaultCurrency" TEXT NOT NULL DEFAULT 'CLP',
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "storeStatus" "StoreStatus" NOT NULL DEFAULT 'OPEN',
    "showOutOfStock" BOOLEAN NOT NULL DEFAULT true,
    "allowPurchaseWithoutStock" BOOLEAN NOT NULL DEFAULT false,
    "pricesIncludeTax" BOOLEAN NOT NULL DEFAULT true,
    "minOrderAmount" DECIMAL(12,2),
    "maxOrderAmount" DECIMAL(12,2),
    "maxQuantityPerProduct" INTEGER NOT NULL DEFAULT 99,
    "maxProductsPerOrder" INTEGER NOT NULL DEFAULT 50,
    "supportVisible" BOOLEAN NOT NULL DEFAULT true,
    "availabilityMessage" TEXT,
    "checkoutEnabled" BOOLEAN NOT NULL DEFAULT true,
    "requireVerifiedEmail" BOOLEAN NOT NULL DEFAULT false,
    "requireRut" BOOLEAN NOT NULL DEFAULT false,
    "requireBillingData" BOOLEAN NOT NULL DEFAULT false,
    "allowBoleta" BOOLEAN NOT NULL DEFAULT true,
    "allowFactura" BOOLEAN NOT NULL DEFAULT true,
    "orderExpirationMinutes" INTEGER NOT NULL DEFAULT 60,
    "paymentExpirationMinutes" INTEGER NOT NULL DEFAULT 30,
    "requireTermsAcceptance" BOOLEAN NOT NULL DEFAULT true,
    "termsUrl" TEXT,
    "privacyUrl" TEXT,
    "maxPaymentAttempts" INTEGER NOT NULL DEFAULT 5,
    "reusePendingPaymentIntent" BOOLEAN NOT NULL DEFAULT true,
    "preventDuplicateOrders" BOOLEAN NOT NULL DEFAULT true,
    "flowEnabled" BOOLEAN NOT NULL DEFAULT true,
    "acceptedCurrency" TEXT NOT NULL DEFAULT 'CLP',
    "refundsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "minPaymentAmount" DECIMAL(12,2),
    "maxPaymentAmount" DECIMAL(12,2),
    "commerceOrderPrefix" TEXT NOT NULL DEFAULT '',
    "strictAmountValidation" BOOLEAN NOT NULL DEFAULT true,
    "strictCurrencyValidation" BOOLEAN NOT NULL DEFAULT true,
    "automaticDeliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
    "manualDeliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
    "autoSendAfterPayment" BOOLEAN NOT NULL DEFAULT false,
    "deliveryRetryMax" INTEGER NOT NULL DEFAULT 3,
    "deliveryRetryIntervalMinutes" INTEGER NOT NULL DEFAULT 15,
    "allowPartialDeliveries" BOOLEAN NOT NULL DEFAULT true,
    "allowEmailResend" BOOLEAN NOT NULL DEFAULT true,
    "requireRecentSessionForCredentials" BOOLEAN NOT NULL DEFAULT true,
    "sensitiveLinkExpirationMinutes" INTEGER NOT NULL DEFAULT 60,
    "hideCredentialsByDefault" BOOLEAN NOT NULL DEFAULT true,
    "keysAutoAssign" BOOLEAN NOT NULL DEFAULT true,
    "keysReserveDuringCheckout" BOOLEAN NOT NULL DEFAULT false,
    "keysReserveDurationMinutes" INTEGER NOT NULL DEFAULT 15,
    "keysLowStockThreshold" INTEGER NOT NULL DEFAULT 5,
    "keysStockAlertsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "keysAllowManualReplace" BOOLEAN NOT NULL DEFAULT true,
    "accountsAutoAssign" BOOLEAN NOT NULL DEFAULT false,
    "accountsRequireRecentSession" BOOLEAN NOT NULL DEFAULT true,
    "accountsHideCredentials" BOOLEAN NOT NULL DEFAULT true,
    "accountsAllowReplace" BOOLEAN NOT NULL DEFAULT true,
    "smmAutoSend" BOOLEAN NOT NULL DEFAULT false,
    "smmManualSend" BOOLEAN NOT NULL DEFAULT true,
    "smmMaxRetries" INTEGER NOT NULL DEFAULT 3,
    "smmAllowPartials" BOOLEAN NOT NULL DEFAULT true,
    "smmValidateUrl" BOOLEAN NOT NULL DEFAULT true,
    "smmStuckAlertMinutes" INTEGER NOT NULL DEFAULT 1440,
    "resendEnabled" BOOLEAN NOT NULL DEFAULT true,
    "transactionalEmailsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "adminEmailsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emailOrderCreated" BOOLEAN NOT NULL DEFAULT true,
    "emailPaymentApproved" BOOLEAN NOT NULL DEFAULT true,
    "emailPaymentRejected" BOOLEAN NOT NULL DEFAULT true,
    "emailDeliveryAvailable" BOOLEAN NOT NULL DEFAULT true,
    "emailDeliveryFailed" BOOLEAN NOT NULL DEFAULT true,
    "emailPasswordReset" BOOLEAN NOT NULL DEFAULT true,
    "emailEmailVerification" BOOLEAN NOT NULL DEFAULT true,
    "requireEmailVerifiedForCheckout" BOOLEAN NOT NULL DEFAULT false,
    "reauthForCredentialReveal" BOOLEAN NOT NULL DEFAULT true,
    "auditSettingsChanges" BOOLEAN NOT NULL DEFAULT true,
    "maintenanceMessage" TEXT,
    "estimatedReturnAt" TIMESTAMP(3),
    "allowAdminDuringMaintenance" BOOLEAN NOT NULL DEFAULT true,
    "allowWebhooksDuringMaintenance" BOOLEAN NOT NULL DEFAULT true,
    "allowJobsDuringMaintenance" BOOLEAN NOT NULL DEFAULT true,
    "allowOngoingDeliveriesDuringMaintenance" BOOLEAN NOT NULL DEFAULT true,
    "notifyPaymentFailed" BOOLEAN NOT NULL DEFAULT true,
    "notifyPaymentInconsistent" BOOLEAN NOT NULL DEFAULT true,
    "notifyDeliveryFailed" BOOLEAN NOT NULL DEFAULT true,
    "notifyPaidWithoutDelivery" BOOLEAN NOT NULL DEFAULT true,
    "notifyLowStock" BOOLEAN NOT NULL DEFAULT true,
    "notifyOutOfStock" BOOLEAN NOT NULL DEFAULT true,
    "notifySmmStuck" BOOLEAN NOT NULL DEFAULT true,
    "notifyProviderError" BOOLEAN NOT NULL DEFAULT true,
    "notifyWebhookFailed" BOOLEAN NOT NULL DEFAULT true,
    "notifyHighValueSale" BOOLEAN NOT NULL DEFAULT true,
    "highValueSaleThreshold" DECIMAL(12,2),
    "adminNotificationEmails" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "store_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "admin_settings_events" (
    "id" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "actorUserId" TEXT,
    "actorEmail" TEXT,
    "changes" JSONB,
    "message" TEXT,
    "result" TEXT NOT NULL DEFAULT 'success',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admin_settings_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "admin_settings_events_section_createdAt_idx" ON "admin_settings_events"("section", "createdAt");

-- CreateIndex
CREATE INDEX "admin_settings_events_actorUserId_createdAt_idx" ON "admin_settings_events"("actorUserId", "createdAt");

-- CreateIndex
CREATE INDEX "admin_settings_events_createdAt_idx" ON "admin_settings_events"("createdAt");
