import Link from "next/link";
import { notFound } from "next/navigation";
import { HiOutlineArrowLeft, HiOutlinePaperClip } from "react-icons/hi2";
import { EmailComposer } from "@/components/admin/communications/email-composer";
import { AttachmentDownload } from "@/components/admin/communications/attachment-download";
import { InternalNoteComposer } from "@/components/admin/communications/internal-note-composer";
import { ThreadActions } from "@/components/admin/communications/thread-actions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getCommunicationAdmins, getEmailThread } from "@/lib/communications/email-queries";
import { emailStatusLabels } from "@/lib/communications/status";

function stringList(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }

export default async function EmailThreadPage({ params }: { params: Promise<{ threadId: string }> }) {
  const { threadId } = await params; const [thread, admins] = await Promise.all([getEmailThread(threadId), getCommunicationAdmins()]); if (!thread) notFound();
  const lastInbound = [...thread.messages].reverse().find((message) => message.direction === "INBOUND");
  const to = lastInbound?.replyToAddress ?? lastInbound?.fromAddress ?? thread.user?.email ?? "";
  const replySubject = /^re:/i.test(thread.subject) ? thread.subject : `Re: ${thread.subject}`;
  return <div className="space-y-5"><Link href="/admin/communications/email" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><HiOutlineArrowLeft />Volver a Correo</Link>
    <header className="space-y-3"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="font-heading text-2xl font-semibold">{thread.subject}</h1><Badge variant="secondary">{thread.status}</Badge><Badge variant="outline">Prioridad {thread.priority.toLowerCase()}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{thread.user ? `${thread.user.name} · ${thread.user.email}` : "Sin usuario vinculado"} · {thread.messages.length} mensajes</p></div><ThreadActions threadId={thread.id} status={thread.status} unreadCount={thread.unreadCount} assignedUserId={thread.assignedUserId} admins={admins} /></div><div className="flex flex-wrap gap-2 text-xs text-muted-foreground">{thread.orderId ? <Link className="hover:text-primary" href={`/admin/orders/${thread.orderId}`}>Pedido {thread.orderId.slice(-8).toUpperCase()}</Link> : <span>Sin pedido vinculado</span>}{thread.deliveryId ? <Link className="hover:text-primary" href={`/admin/deliveries/${thread.deliveryId}`}>Entrega {thread.deliveryId.slice(-8).toUpperCase()}</Link> : <span>Sin entrega vinculada</span>}<span>{thread.assignedEmail ? `Asignada a ${thread.assignedEmail}` : "Sin asignar"}</span></div></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="space-y-4" aria-label="Timeline de conversación">{thread.messages.map((message) => <Card key={message.id} className={message.direction === "INBOUND" ? "border-l-4 border-l-primary" : "border-l-4 border-l-emerald-600"}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-4"><div><CardTitle className="text-sm">{message.direction === "INBOUND" ? message.fromName || message.fromAddress || "Remitente" : "Nicodigos"}</CardTitle><p className="mt-1 text-xs text-muted-foreground">Para: {stringList(message.toAddresses).join(", ")}{stringList(message.ccAddresses).length ? ` · CC: ${stringList(message.ccAddresses).join(", ")}` : ""}</p></div><div className="text-right"><Badge variant="outline">{message.direction === "INBOUND" ? "Entrante" : "Saliente"}</Badge><p className="mt-1 text-xs text-muted-foreground"><time dateTime={message.createdAt}>{new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(message.createdAt))}</time></p></div></div></CardHeader><CardContent className="space-y-4"><div className="whitespace-pre-wrap text-sm leading-6">{message.textContent}</div>{message.remoteImages ? <p className="rounded-lg border border-amber-300/60 bg-amber-50 p-2 text-xs text-amber-900 dark:bg-amber-950/20 dark:text-amber-200">Las imágenes remotas fueron bloqueadas para evitar tracking. Se muestra el texto seguro.</p> : null}{message.attachments.length ? <div><p className="mb-2 flex items-center gap-2 text-xs font-medium"><HiOutlinePaperClip />Adjuntos</p><ul className="space-y-1">{message.attachments.map((file) => <li key={file.id} className="flex flex-col gap-2 rounded-lg bg-muted px-3 py-2 text-xs sm:flex-row sm:items-center sm:justify-between"><span>{file.fileName} · {file.mimeType} · {Math.ceil(file.sizeBytes / 1024)} KB · análisis antivirus {file.scanStatus === "NOT_AVAILABLE" ? "no disponible" : file.scanStatus}</span><AttachmentDownload id={file.id} label={file.fileName} /></li>)}</ul></div> : null}<div className="flex flex-wrap gap-2 border-t border-border pt-3 text-xs text-muted-foreground"><Badge variant="secondary">{emailStatusLabels[message.status]}</Badge>{message.deliveredAt ? <span>Entregado {new Intl.DateTimeFormat("es-CL", { dateStyle: "short", timeStyle: "short" }).format(new Date(message.deliveredAt))}</span> : null}{message.events.map((event) => <span key={event.id}>{event.type.replace("email.", "")}</span>)}</div></CardContent></Card>)}
      {thread.notes.map((note) => <div key={note.id} className="rounded-xl border border-amber-300/60 bg-amber-50/50 p-4 dark:bg-amber-950/10"><div className="flex items-center justify-between gap-3"><Badge variant="outline">Nota interna</Badge><time className="text-xs text-muted-foreground" dateTime={note.createdAt}>{new Intl.DateTimeFormat("es-CL", { dateStyle: "short", timeStyle: "short" }).format(new Date(note.createdAt))}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{note.content}</p><p className="mt-2 text-xs text-muted-foreground">{note.authorEmail}</p></div>)}</main>
      <aside className="space-y-4 xl:sticky xl:top-6 xl:self-start"><Card><CardHeader><CardTitle className="text-base">Responder</CardTitle></CardHeader><CardContent><EmailComposer compact threadId={thread.id} defaultTo={to} defaultSubject={replySubject} /></CardContent></Card><InternalNoteComposer threadId={thread.id} /></aside></div>
  </div>;
}
