"use client";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { updateCommunicationPreferencesAction } from "@/lib/actions/communication-preferences";
import { useWebPush } from "@/components/notifications/onesignal-provider";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";

type Preferences = { marketingEmail: boolean; webPushEnabled: boolean; orders: boolean; payments: boolean; deliveries: boolean; smm: boolean; security: boolean; newProducts: boolean; promotions: boolean };
const labels: Array<[keyof Preferences, string, string]> = [["orders", "Pedidos", "Cambios relevantes en tus pedidos"], ["payments", "Pagos", "Confirmaciones y problemas de pago"], ["deliveries", "Entregas", "Contenido disponible y problemas de entrega"], ["smm", "Servicios SMM", "Progreso y acciones requeridas"], ["security", "Seguridad", "Alertas indispensables de tu cuenta"], ["newProducts", "Productos nuevos", "Novedades de catálogo (marketing)"], ["promotions", "Promociones", "Descuentos y campañas (marketing)"]];
export function NotificationPreferences({ initial }: { initial: Preferences }) { const [prefs, setPrefs] = useState(initial); const [pending, startTransition] = useTransition(); const push = useWebPush(); const stateLabels = { unsupported: "No compatibles", blocked: "Bloqueadas por el navegador", inactive: "No activadas", active: "Activadas", unavailable: "Temporalmente no disponibles" }; return <div className="space-y-5"><section className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-heading font-semibold">Notificaciones web</h2><p className="mt-1 text-sm text-muted-foreground">Estado: <strong className="text-foreground">{stateLabels[push.state]}</strong>. El permiso del navegador y tu preferencia son estados distintos.</p></div>{push.state === "active" ? <Button variant="outline" disabled={push.pending} onClick={() => void push.disable()}>Desactivar en este navegador</Button> : <Button disabled={push.pending || ["unsupported", "blocked", "unavailable"].includes(push.state)} onClick={() => void push.requestPermission()}>Activar notificaciones</Button>}</div>{push.state === "blocked" ? <p className="mt-3 rounded-lg bg-muted p-3 text-sm">El navegador bloqueó el permiso. Habilítalo desde el icono de candado de la barra de direcciones y recarga la página.</p> : null}</section><form className="space-y-5" onSubmit={(e) => { e.preventDefault(); startTransition(async () => { const result = await updateCommunicationPreferencesAction({ ...prefs, webPushEnabled: push.state === "active" }); if (result.success) toast.success("Preferencias actualizadas"); else toast.error(result.message); }); }}><section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between gap-4 border-b border-border pb-4"><div><h2 className="font-heading font-semibold">Email de marketing</h2><p className="text-sm text-muted-foreground">Promociones y novedades. No afecta emails operacionales o de seguridad indispensables.</p></div><Switch checked={prefs.marketingEmail} onCheckedChange={(checked) => setPrefs({ ...prefs, marketingEmail: checked })} aria-label="Email de marketing" /></div><div className="divide-y divide-border">{labels.map(([key, label, description]) => { const mandatory = key === "security"; return <div key={key} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-medium">{label}{mandatory ? " · indispensable" : ""}</p><p className="text-xs text-muted-foreground">{description}</p></div><Switch checked={prefs[key]} disabled={mandatory} onCheckedChange={(checked) => setPrefs({ ...prefs, [key]: checked })} aria-label={label} /></div>; })}</div></section><div className="flex justify-end"><Button type="submit" disabled={pending}>{pending ? "Guardando…" : "Guardar preferencias"}</Button></div></form></div>; }
