import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";

export function EmailToolbar({ query }: { query: { q?: string; mailbox: string; state?: string; priority?: string } }) {
  return <div className="space-y-4"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="font-heading text-2xl font-semibold">Correo</h1><p className="mt-1 text-sm text-muted-foreground">Bandeja operativa de Nicodigos, respuestas, enviados y borradores.</p></div><Button nativeButton={false} render={<Link href="/admin/communications/email/compose" />}>Redactar email</Button></header>
    <form className="flex flex-col gap-2 rounded-2xl border border-border bg-card p-3 md:flex-row" action="/admin/communications/email" method="get"><Input name="q" defaultValue={query.q} placeholder="Nombre, email, asunto, pedido o contenido…" aria-label="Buscar correo" className="md:flex-1" /><NativeSelect name="mailbox" defaultValue={query.mailbox} aria-label="Carpeta"><NativeSelectOption value="inbox">Bandeja de entrada</NativeSelectOption><NativeSelectOption value="sent">Enviados</NativeSelectOption><NativeSelectOption value="drafts">Borradores</NativeSelectOption><NativeSelectOption value="archived">Archivados</NativeSelectOption><NativeSelectOption value="spam">Correo no deseado</NativeSelectOption></NativeSelect><NativeSelect name="state" defaultValue={query.state ?? ""} aria-label="Estado"><NativeSelectOption value="">Todos los estados</NativeSelectOption><NativeSelectOption value="unread">Sin leer</NativeSelectOption><NativeSelectOption value="pending">Pendientes</NativeSelectOption><NativeSelectOption value="answered">Respondidas</NativeSelectOption><NativeSelectOption value="mine">Asignadas a mí</NativeSelectOption><NativeSelectOption value="unassigned">Sin asignar</NativeSelectOption></NativeSelect><NativeSelect name="priority" defaultValue={query.priority ?? ""} aria-label="Prioridad"><NativeSelectOption value="">Toda prioridad</NativeSelectOption><NativeSelectOption value="LOW">Baja</NativeSelectOption><NativeSelectOption value="NORMAL">Normal</NativeSelectOption><NativeSelectOption value="HIGH">Alta</NativeSelectOption><NativeSelectOption value="URGENT">Urgente</NativeSelectOption></NativeSelect><Button type="submit" variant="secondary">Aplicar</Button></form>
  </div>;
}
