"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createEmailDraftAction, sendNewEmailAction } from "@/lib/actions/admin-email";
import { createCommunicationAttachmentUploadAction, finalizeCommunicationAttachmentAction } from "@/lib/actions/communication-attachments";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";

function addresses(value: string) { return value.split(/[;,]/).map((item) => item.trim()).filter(Boolean); }

export function EmailComposer({ threadId, messageId, defaultTo = "", defaultSubject = "", defaultContent = "", compact = false }: { threadId?: string; messageId?: string; defaultTo?: string; defaultSubject?: string; defaultContent?: string; compact?: boolean }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [to, setTo] = useState(defaultTo); const [cc, setCc] = useState(""); const [bcc, setBcc] = useState(""); const [subject, setSubject] = useState(defaultSubject); const [content, setContent] = useState(defaultContent); const [kind, setKind] = useState<"OPERATIONAL" | "MARKETING" | "SECURITY" | "SUPPORT">(threadId ? "SUPPORT" : "OPERATIONAL");
  const [currentMessageId, setCurrentMessageId] = useState(messageId); const [attachmentNames, setAttachmentNames] = useState<string[]>([]);
  const [idempotencyKey] = useState(() => crypto.randomUUID());
  const recipientCount = useMemo(() => new Set([...addresses(to), ...addresses(cc), ...addresses(bcc)]).size, [to, cc, bcc]);
  function payload() { return { messageId: currentMessageId, threadId, idempotencyKey, to: addresses(to), cc: addresses(cc), bcc: addresses(bcc), subject, content, kind, confirmMassSend: recipientCount > 10 ? "ENVIAR" : undefined }; }
  return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); startTransition(async () => { const result = await sendNewEmailAction(payload()); if (!result.success) { toast.error(result.message); return; } toast.success("Email aceptado por Resend"); router.push(`/admin/communications/email/${result.data.threadId}`); router.refresh(); }); }}>
    <div className={compact ? "space-y-3" : "grid gap-4 md:grid-cols-2"}><div className="space-y-1.5 md:col-span-2"><Label htmlFor={`to-${threadId ?? "new"}`}>Destinatarios</Label><Input id={`to-${threadId ?? "new"}`} value={to} onChange={(e) => setTo(e.target.value)} placeholder="cliente@ejemplo.cl" required disabled={pending} /><p className="text-xs text-muted-foreground">Separa múltiples direcciones con coma. {recipientCount} destinatario{recipientCount === 1 ? "" : "s"}.</p></div><div className="space-y-1.5"><Label htmlFor="cc">CC</Label><Input id="cc" value={cc} onChange={(e) => setCc(e.target.value)} disabled={pending} /></div><div className="space-y-1.5"><Label htmlFor="bcc">BCC</Label><Input id="bcc" value={bcc} onChange={(e) => setBcc(e.target.value)} disabled={pending} /></div><div className="space-y-1.5 md:col-span-2"><Label htmlFor="subject">Asunto</Label><Input id="subject" value={subject} onChange={(e) => setSubject(e.target.value)} required maxLength={200} disabled={pending} /></div><div className="space-y-1.5"><Label htmlFor="kind">Tipo</Label><NativeSelect id="kind" value={kind} onChange={(e) => setKind(e.target.value as typeof kind)} disabled={pending}><NativeSelectOption value="SUPPORT">Soporte</NativeSelectOption><NativeSelectOption value="OPERATIONAL">Operacional</NativeSelectOption><NativeSelectOption value="SECURITY">Seguridad</NativeSelectOption><NativeSelectOption value="MARKETING">Marketing con consentimiento</NativeSelectOption></NativeSelect></div><div className="space-y-1.5 md:col-span-2"><Label htmlFor="content">Mensaje</Label><Textarea id="content" value={content} onChange={(e) => setContent(e.target.value)} rows={compact ? 7 : 14} required maxLength={50_000} disabled={pending} placeholder="No incluyas keys, contraseñas ni tokens." /><p className="text-xs text-muted-foreground">Editor seguro de texto. La firma y el estilo de Nicodigos se agregan al enviar.</p></div></div>
    <div className="space-y-2"><Label htmlFor={`attachments-${threadId ?? "new"}`}>Adjuntos seguros</Label><Input id={`attachments-${threadId ?? "new"}`} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.csv" disabled={pending || attachmentNames.length >= 10} onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; startTransition(async () => { let draftId = currentMessageId; if (!draftId) { const draft = await createEmailDraftAction(payload()); if (!draft.success) { toast.error(draft.message); return; } draftId = draft.data.messageId; setCurrentMessageId(draftId); } const upload = await createCommunicationAttachmentUploadAction({ messageId: draftId, fileName: file.name, mimeType: file.type, size: file.size }); if (!upload.success) { toast.error(upload.message); return; } const response = await fetch(upload.data.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!response.ok) { toast.error("No se pudo subir el adjunto."); return; } const finalized = await finalizeCommunicationAttachmentAction({ attachmentId: upload.data.attachmentId }); if (!finalized.success) toast.error(finalized.message); else { setAttachmentNames((names) => [...names, file.name]); toast.success("Adjunto agregado"); } }); event.currentTarget.value = ""; }} /><p className="text-xs text-muted-foreground">PDF, imágenes, TXT o CSV · máximo 10 MB y 10 archivos. {attachmentNames.length ? `Adjuntos: ${attachmentNames.join(", ")}` : "Sin adjuntos."}</p></div>
    <div aria-live="polite" className="flex flex-wrap justify-end gap-2"><Button type="button" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await createEmailDraftAction(payload()); if (result.success) { toast.success("Borrador guardado"); setCurrentMessageId(result.data.messageId); router.refresh(); } else { toast.error(result.message); } })}>Guardar borrador</Button><Button type="submit" disabled={pending || recipientCount === 0}>{pending ? "Procesando…" : threadId ? "Responder" : "Enviar email"}</Button></div>
  </form>;
}
