"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createCommunicationTemplateAction } from "@/lib/actions/admin-communication-templates";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";

const variables = ["user.firstName", "order.number", "order.total", "delivery.url", "product.name", "support.email"];
export function TemplateEditor() { const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition(); const router = useRouter(); const [channel, setChannel] = useState<"EMAIL" | "WEB_PUSH">("EMAIL"); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [subject, setSubject] = useState(""); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button />}>Nueva plantilla</DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Nueva plantilla</DialogTitle><DialogDescription>Solo admite variables del catálogo seguro; no ejecuta código.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); startTransition(async () => { const used = variables.filter((variable) => `${subject}${title}${content}`.includes(`{{${variable}}}`)); const result = await createCommunicationTemplateAction({ name, slug, channel, kind: "OPERATIONAL", status: "DRAFT", subject: channel === "EMAIL" ? subject : undefined, title: channel === "WEB_PUSH" ? title : undefined, content, variables: used }); if (!result.success) toast.error(result.message); else { toast.success("Plantilla creada"); setOpen(false); router.refresh(); } }); }}><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label htmlFor="template-name">Nombre</Label><Input id="template-name" value={name} onChange={(e) => setName(e.target.value)} required /></div><div className="space-y-1"><Label htmlFor="template-slug">Slug</Label><Input id="template-slug" value={slug} onChange={(e) => setSlug(e.target.value)} required pattern="[a-z0-9-]+" /></div><div className="space-y-1"><Label htmlFor="template-channel">Canal</Label><NativeSelect id="template-channel" value={channel} onChange={(e) => setChannel(e.target.value as typeof channel)}><NativeSelectOption value="EMAIL">Email</NativeSelectOption><NativeSelectOption value="WEB_PUSH">Web push</NativeSelectOption></NativeSelect></div>{channel === "EMAIL" ? <div className="space-y-1"><Label htmlFor="template-subject">Asunto</Label><Input id="template-subject" value={subject} onChange={(e) => setSubject(e.target.value)} required /></div> : <div className="space-y-1"><Label htmlFor="template-title">Título</Label><Input id="template-title" value={title} onChange={(e) => setTitle(e.target.value)} required /></div>}</div><div className="space-y-1"><Label htmlFor="template-content">Contenido</Label><Textarea id="template-content" rows={10} value={content} onChange={(e) => setContent(e.target.value)} required /><p className="text-xs text-muted-foreground">Variables permitidas: {variables.map((v) => `{{${v}}}`).join(", ")}</p></div><div className="flex justify-end"><Button type="submit" disabled={pending}>{pending ? "Guardando…" : "Crear borrador"}</Button></div></form></DialogContent></Dialog>; }
